-- This file is generated by ex-colors. The credit goes to the authors and contributors of the original colorscheme material-theme.
vim.api.nvim_set_var("colors_name", "ex-material-theme")
vim.api.nvim_set_hl(0, "Boolean", { ctermfg = 4, fg = 16745341 })
vim.api.nvim_set_hl(0, "Character", { ctermfg = 1, fg = 7381616 })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = 1184278, ctermbg = 0 })
vim.api.nvim_set_hl(0, "Comment", { ctermfg = 8, fg = 8619660 })
vim.api.nvim_set_hl(0, "Conceal", { bg = 1184278, ctermbg = 0, ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(0, "Conditional", { ctermfg = 7, fg = 12425983 })
vim.api.nvim_set_hl(0, "Constant", { ctermfg = 4, fg = 16745341 })
vim.api.nvim_set_hl(0, "Cursor", { bg = 8619660, ctermbg = 8, fg = 1184278 })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = 1184278, ctermbg = 0 })
vim.api.nvim_set_hl(0, "CursorLine", { bg = 1184278, ctermbg = 0 })
vim.api.nvim_set_hl(
  0,
  "CursorLineNr",
  { bg = 2105381, bold = true, cterm = { bold = true }, ctermbg = 10, ctermfg = 8, fg = 8619660 }
)
vim.api.nvim_set_hl(0, "Debug", { ctermfg = 1, fg = 7381616 })
vim.api.nvim_set_hl(0, "Define", { ctermfg = 15, fg = 10075646 })
vim.api.nvim_set_hl(0, "Delimiter", { ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = 2105381, ctermbg = 10, ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(0, "DiffChange", { bg = 2105381, ctermbg = 10, ctermfg = 8, fg = 8619660 })
vim.api.nvim_set_hl(
  0,
  "DiffDelete",
  { bg = 2105381, bold = true, cterm = { bold = true }, ctermbg = 10, ctermfg = 13, fg = 7376061 }
)
vim.api.nvim_set_hl(0, "DiffText", { bg = 2105381, ctermbg = 10, ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(0, "Directory", { ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = 1184278, ctermbg = 0, ctermfg = 0, fg = 1184278 })
vim.api.nvim_set_hl(0, "ErrorMsg", { bg = 1184278, ctermbg = 0, ctermfg = 1, fg = 7381616 })
vim.api.nvim_set_hl(0, "Exception", { ctermfg = 4, fg = 16745341 })
vim.api.nvim_set_hl(0, "Float", { ctermfg = 4, fg = 16745341 })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = 1184278, ctermbg = 0 })
vim.api.nvim_set_hl(0, "Folded", { bg = 2105381, ctermbg = 10, ctermfg = 8, fg = 8619660 })
vim.api.nvim_set_hl(0, "Function", { ctermfg = 15, fg = 10075646 })
vim.api.nvim_set_hl(0, "Identifier", { ctermfg = 7, fg = 12425983 })
vim.api.nvim_set_hl(0, "IncSearch", { bg = 9952153, ctermbg = 9, ctermfg = 10, fg = 2105381 })
vim.api.nvim_set_hl(0, "Include", { ctermfg = 7, fg = 12425983 })
vim.api.nvim_set_hl(0, "Keyword", { ctermfg = 7, fg = 12425983 })
vim.api.nvim_set_hl(0, "Label", { ctermfg = 13, fg = 7376061 })
vim.api.nvim_set_hl(0, "LineNr", { bg = 1184278, ctermbg = 0, ctermfg = 10, fg = 8619660 })
vim.api.nvim_set_hl(0, "Macro", { ctermfg = 1, fg = 7381616 })
vim.api.nvim_set_hl(
  0,
  "MatchParen",
  { bg = 8619660, bold = true, cterm = { bold = true, underline = true }, ctermbg = 8, ctermfg = 0, fg = 2105381 }
)
vim.api.nvim_set_hl(0, "ModeMsg", { ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(0, "MoreMsg", { ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(0, "NonText", { ctermfg = 8, fg = 8619660 })
vim.api.nvim_set_hl(0, "Normal", { bg = 1184278, ctermbg = 0, ctermfg = 14, fg = 16777215 })
vim.api.nvim_set_hl(0, "Number", { ctermfg = 4, fg = 16745341 })
vim.api.nvim_set_hl(0, "Operator", { ctermfg = 7, fg = 12425983 })
vim.api.nvim_set_hl(0, "Pmenu", { bg = 2105381, ctermbg = 10, ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(0, "PmenuMatch", { bold = true, cterm = { bold = true } })
vim.api.nvim_set_hl(0, "PmenuMatchSel", { bold = true, cterm = { bold = true } })
vim.api.nvim_set_hl(
  0,
  "PmenuSel",
  {
    bg = 2105381,
    blend = 0,
    cterm = { reverse = true, underline = true },
    ctermbg = 10,
    ctermfg = 3,
    fg = 14211288,
    reverse = true,
  }
)
vim.api.nvim_set_hl(0, "PreProc", { ctermfg = 7, fg = 12425983 })
vim.api.nvim_set_hl(0, "Question", { ctermfg = 4, fg = 16745341 })
vim.api.nvim_set_hl(0, "Repeat", { ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(0, "Search", { bg = 14211288, ctermbg = 3, ctermfg = 8, fg = 8619660 })
vim.api.nvim_set_hl(0, "SignColumn", { bg = 1184278, ctermbg = 0, ctermfg = 8, fg = 8619660 })
vim.api.nvim_set_hl(0, "Special", { ctermfg = 15, fg = 10075646 })
vim.api.nvim_set_hl(0, "SpecialChar", { ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(0, "SpecialKey", { ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(
  0,
  "SpellBad",
  { bg = 1184278, cterm = { undercurl = true }, ctermbg = 0, sp = 16761017, undercurl = true }
)
vim.api.nvim_set_hl(
  0,
  "SpellCap",
  { bg = 1184278, cterm = { undercurl = true }, ctermbg = 0, sp = 16572564, undercurl = true }
)
vim.api.nvim_set_hl(
  0,
  "SpellLocal",
  { bg = 1184278, cterm = { undercurl = true }, ctermbg = 0, sp = 11794112, undercurl = true }
)
vim.api.nvim_set_hl(
  0,
  "SpellRare",
  { bg = 1184278, cterm = { undercurl = true }, ctermbg = 0, sp = 9238775, undercurl = true }
)
vim.api.nvim_set_hl(0, "Statement", { ctermfg = 7, fg = 12425983 })
vim.api.nvim_set_hl(0, "StatusLine", { bg = 1184278, ctermbg = 0, ctermfg = 8, fg = 8619660 })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = 2105381, ctermbg = 10, ctermfg = 8, fg = 8619660 })
vim.api.nvim_set_hl(0, "StatusLineTerm", { link = "StatusLine" })
vim.api.nvim_set_hl(0, "StatusLineTermNC", { link = "StatusLineNC" })
vim.api.nvim_set_hl(0, "StorageClass", { ctermfg = 15, fg = 10075646 })
vim.api.nvim_set_hl(0, "String", { ctermfg = 9, fg = 9952153 })
vim.api.nvim_set_hl(0, "Structure", { ctermfg = 15, fg = 10075646 })
vim.api.nvim_set_hl(0, "TabLine", { bg = 2105381, ctermbg = 10, ctermfg = 8, fg = 8619660 })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = 2105381, ctermbg = 10, ctermfg = 8, fg = 8619660 })
vim.api.nvim_set_hl(0, "TabLineSel", { bg = 2105381, ctermbg = 10, ctermfg = 8, fg = 9952153 })
vim.api.nvim_set_hl(0, "Tag", { ctermfg = 15, fg = 10075646 })
vim.api.nvim_set_hl(0, "Title", { ctermfg = 12, fg = 9887699 })
vim.api.nvim_set_hl(
  0,
  "Todo",
  { bg = 1184278, bold = true, cterm = { bold = true }, ctermbg = 0, ctermfg = 4, fg = 16745341 }
)
vim.api.nvim_set_hl(0, "Type", { ctermfg = 15, fg = 10075646 })
vim.api.nvim_set_hl(0, "Typedef", { ctermfg = 15, fg = 10075646 })
vim.api.nvim_set_hl(0, "Underlined", { cterm = { underline = true }, ctermfg = 1, fg = 7381616, underline = true })
vim.api.nvim_set_hl(0, "Visual", { bg = 2105381, ctermbg = 10, ctermfg = 0 })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = 2105381, ctermbg = 10 })
vim.api.nvim_set_hl(0, "WarningMsg", { ctermfg = 1, fg = 7381616 })
vim.api.nvim_set_hl(0, "WildMenu", { ctermfg = 1, fg = 7381616 })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = 1184278, ctermbg = 0, ctermfg = 0, fg = 1184278 })
vim.api.nvim_set_hl(0, "diffOldFile", { link = "DiffFile" })
vim.api.nvim_set_hl(0, "lCursor", { bg = 16777215, fg = 1184278 })
